### PR TITLE
fix #58 fix #57

### LINKED ISSUE #57: Back to home dosn't work
On the "Data got Uploaded" page the back to home button doesn't work!

### LINKED ISSUE #58: Incorrect linking
On the Screen "I have typical symptoms" the link of "i have a positive test result" is set to the homescreen...

### PR DESCRIPTION
**Pull request by kreativmonkey**

### CODE REVIEW

File: App/screens/DataUpload.tsx [hunk 1]
```diff
@@ -28,7 +28,7 @@ export class DataUpload extends React.Component<{
         </Text>
         <Button
           title="Back to home"
-          onPress={() => this.props.navigation.navigate('Home')}
+          onPress={() => navigation.navigate('HomeBluetooth')}
```
Comment (haveyaseen) [inline App/screens/DataUpload.tsx:31]: Please re-add `this.props.`
